parameter_defaults:

  # List of enabled Image Import Methods. Valid values in the list are 'glance-direct' and 'web-download'
  GlanceEnabledImportMethods: web-download
  # URI that specifies the staging location to use when importing images
  GlanceNodeStagingUri: file:///var/lib/glance/staging

  # The short name of the Glance backend to use. Should be one of swift, rbd, cinder, or file
  GlanceBackend: file
  # NFS share to mount point for image storage
  GlanceNfsMount: '/var/lib/glance/images'
  # NFS mount options for image storage (when GlanceNfsEnabled is true)
  GlanceNfsOptions: _netdev,bg,intr,context=system_u:object_r:glance_var_lib_t:s0
  # NFS share to mount for image storage
  GlanceNfsFirstServer: '10.151.109.132:/glance'
  # NFS share to mount for image storage
  GlanceNfsSecondServer: '10.151.109.133:/glance'
  # Boolean to enable or not NFS Session Trunking
  # https://bugzilla.redhat.com/show_bug.cgi?id=1683207
  GlanceNfsEnableTrunking: false

  # NFS share to mount point for image storage
  GlanceStagingNfsMount: '/var/lib/glance/staging'
  # NFS mount options for NFS image import staging
  GlanceStagingNfsOptions: _netdev,bg,intr,context=system_u:object_r:glance_var_lib_t:s0
  # NFS share to mount for image import staging
  GlanceStagingNfsFirstServer: '10.151.109.133:/glance_staging'
  # NFS share to mount for image import staging
  GlanceStagingNfsSecondServer: '10.151.109.132:/glance_staging'
  # Boolean to enable or not NFS Session Trunking
  # https://bugzilla.redhat.com/show_bug.cgi?id=1683207
  GlanceStagingNfsEnableTrunking: false

  # NFS share to mount point for metrics storage
  GnocchiNfsMount: '/var/lib/gnocchi'
  # NFS mount options for NFS metrics storage
  GnocchiNfsOptions: _netdev,bg,intr,context=system_u:object_r:var_lib_t:s0
  # NFS share to mount for metrics storage
  GnocchiNfsFirstServer: '10.151.109.136:/gnocchi'
  # NFS share to mount for metrics storage
  GnocchiNfsSecondServer: '10.151.109.135:/gnocchi'
  # Boolean to enable or not NFS Session Trunking
  # https://bugzilla.redhat.com/show_bug.cgi?id=1683207
  GnocchiNfsEnableTrunking: false
  # Gnocchi Storage backend:  swift, rbd, file or s3
  GnocchiBackend: 'file'

  # Cinder Backup backend can be either 'ceph', 'swift' or 'nfs'.
  CinderBackupBackend: nfs
  # NFS share to be mounted
  CinderBackupNfsShare: '10.151.109.135:/cinder_backup'
  # NFS mount options for backup storage
  CinderBackupNfsMountOptions: _netdev,bg,intr,context=system_u:object_r:cinder_var_lib_t:s0

  # NFS share to mount point for nova ephemeral storage
  NovaNfsMount: '/var/lib/nova/instances'
  # NFS mount options for NFS nova ephemeral storage
  NovaNfsOptions: context=system_u:object_r:nfs_t:s0
  # NFS share to mount for nova ephemeral storage
  NovaNfsFirstServer: '10.151.109.134:/nova_ephemeral'
  # NFS share to mount for nova ephemeral storage
  NovaNfsSecondServer: '10.151.109.135:/nova_ephemeral'
  # Boolean to enable or not NFS Session Trunking
  # https://bugzilla.redhat.com/show_bug.cgi?id=1683207
  NovaNfsEnableTrunking: false

