parameter_defaults:
  # Metadata through Neutron DHCP
  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true

  # Neutron Logical bridge mapping between a custom name and OVS bridge
  NeutronBridgeMappings: 'datacentre:br-ex'

  # Neutron VLAN range per bridge
  NeutronNetworkVLANRanges: 'datacentre'

  # Neutron Flat Network
  NeutronFlatNetworks: 'datacentre'

  # Default MTU for the overlay network making sure the VM always gets standard the 1500 byte
  NeutronGlobalPhysnetMtu: 1558

  # Security Group
  NeutronFirewallDriver: 'openvswitch'
